### ISSUE TITLE
TypeError: value is undefined in Firefox when using @font-face

### ISSUE THREAD

**Issue by andreymal** [felixfbecker/dom-to-svg#97]
HTML:

```html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="fontface.css" />
</head>
<body>
<div class="foo">bar</div>
</body>
</html>
```

CSS:

```css
@font-face {
  font-family: Roboto;
  font-style: normal;
  font-weight: 300;
  src: local('Roboto Light');
}

.foo {
  font-family: Roboto;
  font-weight: 300;
}
```

Chrome works fine, but when trying to `documentToSVG(document)` in Firefox, dom-to-svg throws this error:

```
TypeError: value is undefined
    exports parse.js:29
    ValueParser index.js:8
    ValueParser index.js:11
    elementToSVG index.ts:44
    documentToSVG index.ts:12
```

It's caused by this line:

https://github.com/felixfbecker/dom-to-svg/blob/a377921df57ce46da14afa1303ef04c465032f0c/src/index.ts#L43

For some reason `rule.style.src` works fine in Chrome but is `undefined` in Firefox.

It seems this can be replaced with `rule.style.getPropertyValue('src')` — it works for both Chrome and Firefox.
